version: 2.1
jobs:
  check_bash:
    docker:
      - image: koalaman/shellcheck:v0.9.0
    steps:
      - checkout
      - run:
          name: Create .env file from example
          command: mv .env.example .env
      - run:
          name: Run static analysis on bash scripts
          command: ./dev-scripts/check-bash
workflows:
  test:
    jobs:
      - check_bash
