version: 2.1
jobs:
  check_bash:
    docker:
      - image: koalaman/shellcheck-alpine:v0.9.0
    steps:
      - run:
          name: Install dependencies
          command: apk add bash git openssh-client
      - checkout
      - run:
          name: Create settings file from example
          command: mv settings.example.sh settings.sh
      - run:
          name: Run static analysis on bash scripts
          command: ./dev-scripts/check-bash
workflows:
  test:
    jobs:
      - check_bash
