version: 2.1
jobs:
  check_bash:
    docker:
      - image: koalaman/shellcheck-alpine:v0.8.0
    steps:
      - run:
          name: Install dependencies
          command: apk add bash git openssh-client
      - checkout
      - run:
          name: Create settings file from example
          command: mv settings.example.sh settings.sh
      - run:
          name: Run static analysis on bash scripts
          command: |
            while read -r filepath; do
              # Check shebang for bash.
              if head -n 1 "${filepath}" | grep --quiet --regexp 'bash'; then
                  BASH_SCRIPTS+=("${filepath}")
              fi
            done < <(git ls-files)
workflows:
  test:
    jobs:
      - check_bash
